### ISSUE TITLE
Great tool for linux users!  I need a way to open two separate instances with different profiles

### ISSUE THREAD

**Issue by pterodyne** [agam778/MS-365-Electron#152]
Thanks again, I use this daily.  The only issue is: I need a way to run o_ne instance_ to hit my 20 or so o365 **admin** accounts  (this would be set to target the same window when clicking on stuff so I don't get kicked out of the PWA window when going to the Exchange admin portal for example.)

Then _another instance_ that uses the my actual o365 **user** account for accessing word/excel documents in sharepoint etc. Ideally they would be a different color icon.  I temporarily got this working by installing a much older version that has a different icon, .7 I think, but it errors out on opening files in new windows for some reason. 

This never was an issue before as I used to use Ubuntu, and there was a snap that must have been older (or a different developer, as it had a different icon, and then I also ran **this** version as a Deb and had two functional versions with different icons and sessions. But now I have switched to Debian 12, and won't be installing snap :).  I have tried other electron versions available on github and elsewhere and normal PWAs. But they all have shortcomings. I even used nativfier to make my own, but when I did that the .desktop icon launches the right electron app, but is not connected to the favorited icon, and as such makes 2 icons per instance which just rubs my ocd the wrong way.  Or they target a new window in chrome in a tab which is also annoying.  Your version is perfect, other than the ask herein.

Let me know if you can think of a way

Thanks again!

Bryan.

**Comment by pterodyne** [comment]
Interestingly enough I just installed a deb for the last 0.7.3 over 0.7.0 and I can now open in new windows without an error.  There is still an error screen when first opening, but works after that.

Probably not the best way since it is older, but at least it is working for now.
I'm guessing it is working because it has a different name.  I suppose another way I could approach this is to fork it and make one specificaly for "admin.microsoft.com" website instead, with a different icon.

**Comment by agam778** [comment]
Hi! I am sorry for not replying to this issue, but I need to prioritize my studies at the moment due to personal reasons, and my exams are approaching as well. I'll still try my best to find some time and fix this. I hope you understand.

**Comment by agam778** [comment]
Hi! Actually, since I do not have much time to spend on this app, I came up with a temporary and quick solution. Basically, in the menu bar, I'll be adding two options, like this:

![image](https://github.com/agam778/MS-365-Electron/assets/68941022/32c6a5a2-44f7-458f-81db-032d43de8aca)

The first option would open Microsoft 365 Web with your personal account (https://microsoft365.com/?auth=1), and other one would open MS 365 Web with your Work/School account (https://microsoft365.com/?auth=2), which is basically what I do in the "Open Enterprise Version" or "Open Normal version", the difference is that these options change the default page, while this opens them for the current session only.

Would this work?

**Comment by agam778** [comment]
Little update: Instead of just loading different URLs, I have created two different sessions, for work/school account and personal account, which would totally separate both accounts, even while normal usage. That should do the work. Is that fine?
