### ISSUE TITLE
Ability to change height and width of every new window created

### ISSUE THREAD

**Issue by DeviDarkL** [agam778/MS-365-Electron#246]
Is it possible to add a feature where we can change this parameter? "Override height and width of every new window created "

Everytime I open a link to a document a new windows opens with a "default" size. Since I have a resolution of 4k it is very small. I have to resize the window EVERYTIME I open a doc. 

Thank you for this project

**Comment by agam778** [comment]
Hi! I have set the default size of the main window to take 71% width and 74% height of the total resolution by default, which can be changed from the menu. Along with that, every new window created will be a bit smaller (7%) than the size of the default window set by the user.<br>

<img alt="CleanShot 2024-07-22 at 12 17 09" src="https://github.com/user-attachments/assets/60eec1c3-3edf-48f9-97a5-a8528b52a816" width=60% height=auto><br>

https://github.com/user-attachments/assets/43a20cd6-5c4a-4acd-a11c-3afa713e4233

Do you want a separate setting to change the default size of every "new" window created as well?

**Comment by DeviDarkL** [comment]
What you showed me is enough and what i would like :) The problem is that I don't have that option in Ubuntu (installed the app from Ubuntu's app store)

![Captura de ecrã de 2024-07-28 13-26-27](https://github.com/user-attachments/assets/91bc5ec5-d16e-485f-9c0a-bb172625794e)

**Comment by agam778** [comment]
Great! This feature will be added in the app's new update, but if you want to install it right now, you can install the dev version, which includes all the commits after the last release with that feature. The dev version isn't tested but I'm sure it would be stable.

Since you installed it from the Ubuntu app store, which means you installed the snap package, you can download `ubuntu-latest-dist` from https://github.com/agam778/MS-365-Electron/actions/runs/10132658589 and manually install the snap file included in the zip.

Or you can wait for the new update :)

**Comment by DeviDarkL** [comment]
Thank you so much, I will install the dev version to try it out :)

**Comment by agam778** [comment]
So may I close the issue now?

**Comment by agam778** [comment]
No worries!

**Comment by agam778** [comment]
No worries!
