### ISSUE TITLE
Crashes on Maximize

### ISSUE THREAD

**Issue by MomenGDS** [agam778/MS-365-Electron#276]
After opening apps (ex: word), and you try to maximize the window, the entire app crashes and closes and in some cases sign out.

Device: Dell Laptop
Os: Kali Linux amd64

**Comment by agam778** [comment]
This issue is known and has been fixed (it was an electron issue), but I haven't released a new version yet, so for now you'll have to use the developer version (which I think is stable, although I didn't test it much yet) which you can download it from here under "Artifacts": https://github.com/agam778/MS-365-Electron/actions/runs/10702144981

**Comment by Sithuk** [comment]
Any update when the new version will be released that has the fix for the crash on maximise?
